[tool.bumpversion]
current_version = "3.6.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = false
allow_dirty = false
commit = false

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = "deepl-rb.gemspec"
search = "{current_version}"
replace = "{new_version}"

[[tool.bumpversion.files]]
filename = "lib/version.rb"
search = "{current_version}"
replace = "{new_version}"

